
package ma.enset.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://webService.enset.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://webService.enset.ma/", className = "ma.enset.proxy.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://webService.enset.ma/", className = "ma.enset.proxy.ConversionResponse")
    @Action(input = "http://webService.enset.ma/BanqueService/conversionRequest", output = "http://webService.enset.ma/BanqueService/conversionResponse")
    public double conversion(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @return
     *     returns ma.enset.proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://webService.enset.ma/", className = "ma.enset.proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://webService.enset.ma/", className = "ma.enset.proxy.GetCompteResponse")
    @Action(input = "http://webService.enset.ma/BanqueService/getCompteRequest", output = "http://webService.enset.ma/BanqueService/getCompteResponse")
    public Compte getCompte();

    /**
     * 
     * @return
     *     returns java.util.List<ma.enset.proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://webService.enset.ma/", className = "ma.enset.proxy.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://webService.enset.ma/", className = "ma.enset.proxy.GetComptesResponse")
    @Action(input = "http://webService.enset.ma/BanqueService/getComptesRequest", output = "http://webService.enset.ma/BanqueService/getComptesResponse")
    public List<Compte> getComptes();

}
